server:
  port: 8095


spring:
# DataSource Settings
  datasource:
    url: jdbc:h2:mem:dss-db
    username: sa

    driverClassName: org.h2.Driver

  # JPA Serrings
    jpa:
      database: H2
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        show-sql: true